#!/usr/bin/env python3
"""
sid_extract.py - Parse a PSID/RSID file and emit:
  - <out>/loader_sid.bin : raw C64 binary (without the SID header)
  - <out>/loader_sid.inc : 64tass include defining SID_LOAD/SID_INIT/SID_PLAY
                          and binary-including the .bin at SID_LOAD.

Usage:
  python3 scripts/tools/sid_extract.py <input.sid> <output_dir>

Notes:
  - The SID file itself is NOT redistributed by this repo. Obtain it from
    HVSC (https://hvsc.c64.org/) and place it locally (gitignored).
  - PSID v1 header = 0x76 bytes; PSID v2NG/RSID = 0x7C bytes. We read the
    declared dataOffset field (big-endian uint16 at offset 6) so it works
    for both.
  - If `loadAddress` field is 0, the first 2 bytes of `data` are the actual
    load address (little-endian, classic CBM PRG header). Otherwise the
    `loadAddress` header field is used and `data` is raw.
"""
from __future__ import annotations
import os, struct, sys

def die(msg: str) -> None:
    print(f"sid_extract: {msg}", file=sys.stderr)
    sys.exit(1)

def main() -> None:
    if len(sys.argv) != 3:
        die("usage: sid_extract.py <input.sid> <output_dir>")
    src, outdir = sys.argv[1], sys.argv[2]
    if not os.path.isfile(src):
        die(f"input not found: {src}")
    with open(src, "rb") as f:
        blob = f.read()
    if len(blob) < 0x7C:
        die("file too small to be a SID")

    magic = blob[0:4]
    if magic not in (b"PSID", b"RSID"):
        die(f"not a PSID/RSID file (magic={magic!r})")

    # All multi-byte header fields are big-endian.
    version       = struct.unpack(">H", blob[4:6])[0]
    data_offset   = struct.unpack(">H", blob[6:8])[0]
    load_addr_hdr = struct.unpack(">H", blob[8:10])[0]
    init_addr     = struct.unpack(">H", blob[10:12])[0]
    play_addr     = struct.unpack(">H", blob[12:14])[0]

    payload = blob[data_offset:]
    if load_addr_hdr == 0:
        if len(payload) < 2:
            die("payload too small for embedded load address")
        load_addr = payload[0] | (payload[1] << 8)
        bin_data  = payload[2:]
    else:
        load_addr = load_addr_hdr
        bin_data  = payload

    if init_addr == 0:
        init_addr = load_addr
    if play_addr == 0:
        die("SID has no play address (driver-driven SIDs are not supported)")

    end_addr = load_addr + len(bin_data) - 1
    if end_addr > 0xFFFF:
        die(f"SID extends past $FFFF (load=${load_addr:04X}, size={len(bin_data)})")

    os.makedirs(outdir, exist_ok=True)
    bin_path = os.path.join(outdir, "loader_sid.bin")
    inc_path = os.path.join(outdir, "loader_sid.inc")

    with open(bin_path, "wb") as f:
        f.write(bin_data)

    rel_bin = os.path.relpath(bin_path, start=os.path.dirname(inc_path)) \
        if os.path.dirname(inc_path) else bin_path

    with open(inc_path, "w") as f:
        f.write(
            "; Auto-generated by scripts/tools/sid_extract.py - DO NOT EDIT\n"
            f"; Source SID: {os.path.basename(src)}\n"
            f"; PSID version: {version}\n"
            f"; load=${load_addr:04X} end=${end_addr:04X} "
            f"init=${init_addr:04X} play=${play_addr:04X} size={len(bin_data)}\n"
            f"SID_PRESENT = 1\n"
            f"SID_LOAD = ${load_addr:04X}\n"
            f"SID_INIT = ${init_addr:04X}\n"
            f"SID_PLAY = ${play_addr:04X}\n"
            f"SID_SIZE = {len(bin_data)}\n"
            "; The actual payload bytes are emitted inline by the loader\n"
            "; (label `sid_payload`) and copied to SID_LOAD at startup, so\n"
            "; the resulting PRG stays compact (no big $0A00..SID_LOAD gap).\n"
        )

    print(f"sid_extract: load=${load_addr:04X} end=${end_addr:04X} "
          f"init=${init_addr:04X} play=${play_addr:04X} "
          f"size={len(bin_data)} bytes")
    print(f"sid_extract: wrote {bin_path}")
    print(f"sid_extract: wrote {inc_path}")

if __name__ == "__main__":
    main()
